Refactors based on jrddunbr's ideas and general cleanup
age-series/libage pull request #19
Opened 2023-02-25 23:37 UTC by empireu

- Makes Scale generic and moves units to more appropriate packages
- Moves Thermal Constructs and simulator to a separate file

2023-02-25 23:56 UTC, jrddunbr requested changes
Some nits.

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/measurement/Scale.kt
> +}
Missing newline at end of file.

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/measurement/ThermalUnits.kt
> +}
Missing newline at end of file.

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/thermal/Constructs.kt
> + *
Still doesn't cover _what_ STP it is. There are multiple standards. Please specify the centigrade equivalent in the comment.

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/thermal/Simulation.kt
> +}
Missing newline.

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/constant/Material.kt
> +    abstract val specificHeat: Double
Nice catch.

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/thermal/Constructs.kt
> +    operator fun div(rhs: Double) = Temperature(kelvin / rhs)
No, it doesn't really make sense in most cases imo.

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/thermal/Constructs.kt
> +}
Missing newline

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/thermal/Constructs.kt
> +value class Temperature(val kelvin: Double) {
Might want `open` if we extend it as a serializable.

2023-02-25 23:56 UTC, jrddunbr commented on src/main/kotlin/org/ageseries/libage/sim/thermal/Constructs.kt
> +data class ThermalConnectionParameters(
Might want to use `open` here if we want to extend it with a serializable version.

2023-02-26 05:48 UTC, jrddunbr commented
Merge conflicts.

2023-02-26 11:52 UTC, Grissess commented
This _may_ have been accidentally rendered moot by my own pushes on #18 , but I'm open to cherry-picking some of these in anyway.

And some other changes as well: clarifying STP is on me, where we're using the IUPAC standard at 0C (NIST prefers 20C). Realistically, that value in Kelvin is exactly the difference between the zero points on centigrade and Kelvin :)

2023-02-26 15:04 UTC, closed without merging